/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flyscale_chapter_5_NativeVideoPlayer */

#ifndef _Included_com_flyscale_chapter_5_NativeVideoPlayer
#define _Included_com_flyscale_chapter_5_NativeVideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flyscale_chapter_5_NativeVideoPlayer
 * Method:    getStringFromJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flyscale_chapter_15_NativeVideoPlayer_getStringFromJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_flyscale_chapter_5_NativeVideoPlayer
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flyscale_chapter_15_NativeVideoPlayer_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
